name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: ./app

      - name: Upload APK
        uses: ./.github/actions/upload-artifact
        with:
          name: app-debug.apk
          path: app/app/build/outputs/apk/debug/app-debug.apk
